name: 'publish-arm64'

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Set up Node 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install Rust stable
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      # Install Ubuntu dependencies for Tauri (ARM64)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf build-essential pkg-config libssl-dev sqlite3 libsqlite3-dev

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm ci

      # Build frontend
      - name: Build Angular frontend
        run: npm run build

      # Install Tauri CLI
      - name: Install Tauri CLI
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          cargo install tauri-cli

      # Build the .deb package for Raspberry Pi
      - name: Build .deb for ARM64
        run: npm run build:pi

      # Publish release using Tauri Action
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__       # automatically replaced by app version in tauri.conf.json
          releaseName: 'MediaScheduler v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: '--target aarch64-unknown-linux-gnu --bundles deb'
